
import java.awt.Dimension;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import javax.swing.UIManager;
import java.sql.*;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author pc
 */
public class LogIn extends javax.swing.JFrame {
    private final DB_Manager db = new DB_Manager();

    /**
     * Creates new form MainUiFrame
     */
    public LogIn() {
        try { System.setOut(new java.io.PrintStream(System.out, true, "UTF-8")); } 
        catch (java.io.UnsupportedEncodingException ex) { ex.printStackTrace(); }
        
        initComponents();
        ImageIcon icon = new ImageIcon("Images/Book_Icon.png");
	Image image = icon.getImage(); // ImageIcon에서 Image 객체 가져오기
        Image scaledImage = image.getScaledInstance(50, 50, java.awt.Image.SCALE_SMOOTH); // 원하는 크기로 조정
        ImageIcon scaledIcon = new ImageIcon(scaledImage);
        BookImage.setIcon(scaledIcon);
        
        IdTextField.setPreferredSize(new Dimension(75, 25));
        PasswordField.setPreferredSize(new Dimension(75, 25));
        LoginButton.setPreferredSize(new Dimension(40, 25));
        MemberLabel.setPreferredSize(new Dimension(64, 25));
        SignupButton.setPreferredSize(new Dimension(67, 30));
        
        SwingUtilities.updateComponentTreeUI(this);
    }
    
//    private void connectToDatabase() {
//        try {
//            String strURL = "jdbc:mysql://localhost:3306/LMS?characterEncoding=UTF-8&serverTimezone=UTC&useSSL=false"; // MySQL의 포트와 데이터베이스명(LMS)을 지정
//            String strUser = "root"; // MySQL 사용자 이름
//            String strPWD = "rootpw"; // MySQL 비밀번호
//            Connection = DriverManager.getConnection(strURL, strUser, strPWD);
//        } catch (SQLException e) {
//            e.printStackTrace();
//        }
//    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Login = new javax.swing.JPanel();
        Container = new javax.swing.JPanel();
        TitleLabel = new javax.swing.JLabel();
        BookImage = new javax.swing.JLabel();
        IdLabel = new javax.swing.JLabel();
        PasswordLabel = new javax.swing.JLabel();
        IdTextField = new javax.swing.JTextField();
        PasswordField = new javax.swing.JPasswordField();
        LoginButton = new javax.swing.JButton();
        SignupButton = new javax.swing.JButton();
        MemberLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 204, 255));
        setPreferredSize(new java.awt.Dimension(1200, 800));

        Login.setBackground(new java.awt.Color(204, 204, 255));
        Login.setPreferredSize(new java.awt.Dimension(1200, 800));
        Login.setLayout(new java.awt.GridBagLayout());

        Container.setBackground(new java.awt.Color(204, 204, 255));
        Container.setPreferredSize(new java.awt.Dimension(500, 300));

        TitleLabel.setFont(new java.awt.Font("나눔바른펜", 1, 24)); // NOI18N
        TitleLabel.setForeground(new java.awt.Color(153, 153, 255));
        TitleLabel.setText("LogIn");
        TitleLabel.setAlignmentX(0.5F);

        BookImage.setText(" ");

        IdLabel.setFont(new java.awt.Font("맑은 고딕", 0, 14)); // NOI18N
        IdLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        IdLabel.setText("아이디");

        PasswordLabel.setFont(new java.awt.Font("맑은 고딕", 0, 14)); // NOI18N
        PasswordLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        PasswordLabel.setText("비밀번호");

        LoginButton.setBackground(new java.awt.Color(153, 153, 255));
        LoginButton.setFont(new java.awt.Font("나눔스퀘어", 0, 12)); // NOI18N
        LoginButton.setText("로그인");
        LoginButton.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        LoginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoginButtonActionPerformed(evt);
            }
        });

        SignupButton.setBackground(new java.awt.Color(204, 204, 255));
        SignupButton.setText("회원가입");
        SignupButton.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        SignupButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SignupButtonActionPerformed(evt);
            }
        });

        MemberLabel.setFont(new java.awt.Font("맑은 고딕", 0, 10)); // NOI18N
        MemberLabel.setForeground(new java.awt.Color(153, 153, 153));
        MemberLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        MemberLabel.setText("회원이 아니시라면?");

        javax.swing.GroupLayout ContainerLayout = new javax.swing.GroupLayout(Container);
        Container.setLayout(ContainerLayout);
        ContainerLayout.setHorizontalGroup(
            ContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ContainerLayout.createSequentialGroup()
                .addGroup(ContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ContainerLayout.createSequentialGroup()
                        .addGap(125, 125, 125)
                        .addGroup(ContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ContainerLayout.createSequentialGroup()
                                .addComponent(MemberLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(SignupButton, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(LoginButton, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(ContainerLayout.createSequentialGroup()
                                .addGroup(ContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(PasswordLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(IdLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(ContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(PasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(IdTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(ContainerLayout.createSequentialGroup()
                        .addGap(209, 209, 209)
                        .addGroup(ContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(TitleLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(BookImage, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(119, Short.MAX_VALUE))
        );
        ContainerLayout.setVerticalGroup(
            ContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ContainerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(BookImage, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TitleLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(IdTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(IdLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(ContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PasswordLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(LoginButton, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(SignupButton, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                    .addComponent(MemberLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(59, Short.MAX_VALUE))
        );

        Login.add(Container, new java.awt.GridBagConstraints());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Login, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Login, javax.swing.GroupLayout.DEFAULT_SIZE, 812, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void LoginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoginButtonActionPerformed
        String userId = IdTextField.getText();                     // 아이디 텍스트 로드
        String password = new String(PasswordField.getPassword()); // 비밀번호 텍스트 로드

        String[] userDetails = db.getUserDetails(userId, password); // user_id와 password 데이터가 Users 테이블에 존재하는지 확인후 해당 회원의 user_pin과 role 반환하는 메소드
        
        if (userDetails[0] != null) {
            JOptionPane.showMessageDialog(this, "로그인 성공!"); // 반환되는 user_pin이 존재하는 경우 로그인 성공

            int userPin = Integer.parseInt(userDetails[0]);
            String role = userDetails[1];

            if ("admin".equalsIgnoreCase(role)) {
                new BookInfo_Admin(userPin).setVisible(true); // role이 admin인 경우 관리자용 인터페이스 활성화
            } else {
                new BookInfo_User(userPin).setVisible(true); // role이 user인 경우 일반 사용자용 인터페이스 활성화
            }
            this.dispose(); // 로그인 창 닫기
        
        } else {
            JOptionPane.showMessageDialog(this, "로그인 실패: 아이디 또는 비밀번호가 잘못되었습니다.", "로그인 오류", JOptionPane.ERROR_MESSAGE); //반환되는 user_pin이 존재하지 않는 경우 로그인 실패
        }
    }//GEN-LAST:event_LoginButtonActionPerformed

    private void SignupButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SignupButtonActionPerformed
        SignUp signUpWindow = new SignUp();
        signUpWindow.setVisible(true);
        this.dispose(); // 현재 로그인 인터페이스 비활성화 (선택사항)
    }//GEN-LAST:event_SignupButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LogIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LogIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LogIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LogIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LogIn().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BookImage;
    private javax.swing.JPanel Container;
    private javax.swing.JLabel IdLabel;
    private javax.swing.JTextField IdTextField;
    private javax.swing.JPanel Login;
    private javax.swing.JButton LoginButton;
    private javax.swing.JLabel MemberLabel;
    private javax.swing.JPasswordField PasswordField;
    private javax.swing.JLabel PasswordLabel;
    private javax.swing.JButton SignupButton;
    private javax.swing.JLabel TitleLabel;
    // End of variables declaration//GEN-END:variables
}
